version: '3'

services:
  app:
    container_name: chatgpt-web
    image: chenzhaoyu94/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 3002:3002
    environment:
      # API Key
      OPENAI_API_KEY:
			# 每小时请求限制
			MAX_REQUEST_PER_HOUR: 1000
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
			# 数据库配置地址
			CHAT_WEB_DATABASE_HOST:
			# 数据库配置端口
			CHAT_WEB_DATABASE_PORT:
			# 数据库配置用户名
			CHAT_WEB_USERNAME:
			# 数据库配置密码
			CHAT_WEB_PASSWORD:
			# 数据库配置数据库名
			CHAT_WEB_DATABASE:
			# JWT密钥
			CHAT_WEB_JWT_SECRET_KEY: wuhu~
